services:
  - type: web
    name: shopverse
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm install --prefix frontend --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
